#!/bin/bash
echo "╔════════════════════════════════════╗"
echo "║⏳  Installing Python dependencies...║"
echo "╚════════════════════════════════════╝"
python3 -m venv env && \
source env/bin/activate && \
pip3 install opencv-python jupyter ipython keras sklearn scipy numpy gym[all] pandas matplotlib six && \
git clone https://github.com/openai/universe && cd universe && \
pip3 install -e . && cd ..
pip3 install https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.1-py3-none-any.whl && \
pip3 install tflearn && \
echo "╔══════════════════════════════════════════════════════════════════════════╗"
echo "║✅  Done. Run: `source env/bin/activate && jupyter notebook` to get started║"
echo "╚══════════════════════════════════════════════════════════════════════════╝"